# Generated by Django 5.2.4 on 2025-09-16 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0010_systemmetrics_usersession_activitylog_pagevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('multiple_failures', 'Multiple Login Failures'), ('suspicious_ip', 'Suspicious IP Address'), ('brute_force', 'Brute Force Attack'), ('invalid_2fa', 'Invalid 2FA Attempts')], max_length=20)),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-attempt_time'],
                'indexes': [models.Index(fields=['username', 'attempt_time'], name='core_applic_usernam_f0eef1_idx'), models.Index(fields=['ip_address', 'attempt_time'], name='core_applic_ip_addr_74f5e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminTwoFactorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_2fa_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'expires_at'], name='core_applic_code_f393aa_idx'), models.Index(fields=['user', 'is_used'], name='core_applic_user_id_6098e8_idx')],
            },
        ),
    ]
