# Generated by Django 5.2.4 on 2025-10-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0011_adminsecurityalert_adminloginattempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('lecturer', 'Lecturer'), ('professor', 'Professor'), ('staff', 'Staff'), ('registrar', 'Registrar'), ('dean', 'Dean'), ('hod', 'Head of Department'), ('hostel_warden', 'Hostel Warden'), ('finance', 'Finance')], max_length=20),
        ),
    ]
